### ISSUE TITLE
Session 1: Resolve play test feedback.

### ISSUE THREAD

**Issue by blinks** [blinks/dreams-in-darkness#1]
> Feels bad to have a spell without any wands.  Feels bad to have no cups at start.  Feels bad to have a need for a specific resource, but no obvious route to acquiring it.

Perhaps each area you control provides you with a resource of its type?  Perhaps new sources can be found in play?

> Feels bad to start the game with a vague "control stuff" objective.

Perhaps points-of-interest can be VP locations, and controlling more of them (or performing more quests based on them) can be the winning condition?

> Feels fiddly to spend resources granularly.

Perhaps you spend cards instead; casting a ritual plays its card, and drawing it back up takes time.  Spending resources is playing a card as well, in this model.  Need to figure out how to even things out still.

> Ace and Court have no obvious numeric value.

If these were instead events -- where the Ace creates a source and the Court cards create points-of-interest for objectives, the map would naturally grow over time.

> The map spaces are difficult to talk about without any names or landmarks.

Generate landmarks at the beginning of the game -- starting areas.  Terrain for them and surrounding spaces.  Mountain ranges, rivers, and roads for borders, all named.  Starting objective points of interest.

**Comment by blinks** [comment]
- The map should have general terrain (including borders) and names for each area at the start.  Some of this could perhaps be player-generated, but hearing all the “March to H3” and “Hold at A4" pulls me right out of the fiction.
- Suits shouldn’t be resources — and players shouldn’t have to be accountants about their stuff.  I think I’ll pull ‘D&D gold’ resources out of the game and just make them abstract.  (In particular, you just eat through conditions to cast spells.)
- Objectives need to be a part of the game setup.  The initial three-card draw can help with this, making it feel more like a normal tarot reading.
- As you mentioned, I think teams aren’t necessary, and that should be made clear.  You should be able to “win” together, though, perhaps helping each other reach objectives.
- If players are ancient dead wizards / elder things, there’s no need for a strict control on public communication, as long as it’s public.  Secrets should still require co-presence.
- Instead of hourly granularity, push everything to the four named times.  This is when your cultists “check-in” (so everything collapses to then anyway), and simplifies the GM’s work immensely.
- I’m worried about making this work in person, but perhaps that’s no big deal.

**Comment by jrtom** [comment]
General observation: the first iteration of this game feels like it it's on the cusp between an RPG and a card-and-map-driven strategy game.  Most of the suggestions here sound like they're moving it toward the latter.  This is not a problem, just an observation.

**Comment by blinks** [comment]
You think it's becoming _less_ RPG-ish?  I thought the other way, personally. :)

**Comment by jrtom** [comment]
Interesting.  Yeah, in part because you're talking about winning conditions and VPs more explicitly (and identifying such conditions that are intrinsic to the game, as opposed to letting goals be exclusively something that the players decide).

**Comment by blinks** [comment]
I think that without explicit goals, it's easy to get lost in options.

**Comment by jrtom** [comment]
I don't disagree with that.  But it's the _kind_ of goals that you're proposing right now that make it feel less RPG-ish to me (VPs especially).  And the fact that one talks about "winning" it at all, really.

**Comment by blinks** [comment]
Noted.
